### PR TITLE
Various grid related bugfixes and improvements. Initial ability to calculate a subset of MEP.

### PR DESCRIPTION
**Pull request by mjw99**
This provides the ability to calculate a set of MEPs on a specific electron density isosurface.

``` bash
# This is an example to calculate the MEP on the 0.002 electon/bohr^3 surface.
property
  grid pad 2.0 step 0.088
  espiso iso 0.002 tol 0.00003
end
```

Also includes an example Travis setup for testing.

### CODE REVIEW

**Comment by jeffhammond** [comment]
Thanks for this.  Just so you know, I am still thinking about how to handle this, because these are nontrivial changes on a topic where I have no scientific expertise.  I will try to connect with someone at PNNL about testing.

**Comment by mjw99** [comment]
Dear Jeff,
Thank you for the update; I really appreciate it.

**Comment by jeffhammond** [comment]
@mjw99 Please don't jump on it quite yet since it is new and I'm not sure when it officially replaces SVN, but https://github.com/nwchemgit/nwchem is online.

**Comment by mjw99** [comment]
Thanks Jeff for the heads-up; exciting news! I am glad the Travis script ended up being of use. Once the dust has settled I will try and offer this pull request there.

**Pull request closed without merging**
